### ISSUE TITLE
No armv7 support

### ISSUE THREAD

**Issue by xenkof** [hardwarehaven/wolnut#13]
Although in your video you mentioned reusing old raspberry Pii for this job, there's no armv7 support included for them.

**Comment by kroshka4aplin** [comment]
In my fork, I added support for building on armv7. It is necessary to add armv7 build support to the workflow, for example like this:

```
text
- name: Build and push multi-arch
  uses: docker/build-push-action@v5
  with:
    context: .
    platforms: linux/amd64,linux/arm64,linux/arm/v7
```
